# FAKE NEWS CLASSIFICATION AND MANUAL TESTING IT

In [1]:
#import the necessary libraries
import pandas as pd
import numpy as np

In [2]:
#read the datasets
df_fake = pd.read_csv("Fake.csv")
df_real = pd.read_csv("True.csv")

In [3]:
#Insert a column class in each dataset stating the news is fake or real
df_fake["class"] = 0
df_real["class"] = 1

In [4]:
df_fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0

In [5]:
df_real.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  class  
0  December 31, 2017       1  
1  December 29, 2017       1  
2  December 31, 2017       1  
3  December 30, 2017       1  
4  December 29, 2017       1

In [6]:
#check its shape
df_fake.shape, df_real.shape

((23481, 5), (21417, 5))

In [7]:
#remaove the last 10 rows of both the datasets for manual testing

fake_manual_testing = df_fake.tail(10)
#Drop these 10 rows from the df_fake dataset
for i in range(23480,23470,-1):
    df_fake.drop([i], axis=0, inplace= True)
    
real_manual_testing = df_real.tail(10)
#Drop these 10 rows from the df_real dataset
for i in range(21416,21406,-1):
    df_real.drop([i], axis=0, inplace=True)



In [8]:
#check its shape
df_fake.shape, df_real.shape

((23471, 5), (21407, 5))

In [9]:
fake_manual_testing.head()

title  \
23471  Seven Iranians freed in the prisoner swap have...   
23472                      #Hashtag Hell & The Fake Left   
23473  Astroturfing: Journalist Reveals Brainwashing ...   
23474          The New American Century: An Era of Fraud   
23475  Hillary Clinton: ‘Israel First’ (and no peace ...   

                                                    text      subject  \
23471  21st Century Wire says This week, the historic...  Middle-east   
23472   By Dady Chery and Gilbert MercierAll writers ...  Middle-east   
23473  Vic Bishop Waking TimesOur reality is carefull...  Middle-east   
23474  Paul Craig RobertsIn the last years of the 20t...  Middle-east   
23475  Robert Fantina CounterpunchAlthough the United...  Middle-east   

                   date  class  
23471  January 20, 2016      0  
23472  January 19, 2016      0  
23473  January 19, 2016      0  
23474  January 19, 2016      0  
23475  January 18, 2016      0

In [10]:
real_manual_testing.head()

title  \
21407  Mata Pires, owner of embattled Brazil builder ...   
21408  U.S., North Korea clash at U.N. forum over nuc...   
21409  U.S., North Korea clash at U.N. arms forum on ...   
21410  Headless torso could belong to submarine journ...   
21411  North Korea shipments to Syria chemical arms a...   

                                                    text    subject  \
21407  SAO PAULO (Reuters) - Cesar Mata Pires, the ow...  worldnews   
21408  GENEVA (Reuters) - North Korea and the United ...  worldnews   
21409  GENEVA (Reuters) - North Korea and the United ...  worldnews   
21410  COPENHAGEN (Reuters) - Danish police said on T...  worldnews   
21411  UNITED NATIONS (Reuters) - Two North Korean sh...  worldnews   

                   date  class  
21407  August 22, 2017       1  
21408  August 22, 2017       1  
21409  August 22, 2017       1  
21410  August 22, 2017       1  
21411  August 21, 2017       1

In [11]:
#Merging the fake and real manual testing datasets
df_manual_testing = pd.concat([fake_manual_testing, real_manual_testing], axis=0)
df_manual_testing

title  \
23471  Seven Iranians freed in the prisoner swap have...   
23472                      #Hashtag Hell & The Fake Left   
23473  Astroturfing: Journalist Reveals Brainwashing ...   
23474          The New American Century: An Era of Fraud   
23475  Hillary Clinton: ‘Israel First’ (and no peace ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   
21407  Mata Pires, owner of embattled Brazil builder ...   
21408  U.S., North Korea clash at U.N. forum over nuc...   
21409  U.S., North Korea clash at U.N. arms forum on ...   
21410  Headless torso could belong to submarine journ...   
21411  North Korea shipments to Syria chemical arms a...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text      subject  \
23471  21st Century Wire says This week, the historic...  Middle-east   
23472   By Dady Chery and Gilbert MercierAll writers ...  Middle-east   
23473  Vic Bishop Waking TimesOur reality is carefull...  Middle-east   
23474  Paul Craig RobertsIn the last years of the 20t...  Middle-east   
23475  Robert Fantina CounterpunchAlthough the United...  Middle-east   
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23477  21st Century Wire says It s a familiar theme. ...  Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23479  21st Century Wire says Al Jazeera America will...  Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east   
21407  SAO PAULO (Reuters) - Cesar Mata Pires, the ow...    worldnews   
21408  GENEVA (Reuters) - North Korea and the United ...    worldnews   
21409  GENEVA (Reuters) - North Korea and the United ...    worldnews   
21410  COPENHAGEN (Reuters) - Danish police said on T...    worldnews   
21411  UNITED NATIONS (Reuters) - Two North Korean sh...    worldnews   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...    worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...    worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...    worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...    worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...    worldnews   

                   date  class  
23471  January 20, 2016      0  
23472  January 19, 2016      0  
23473  January 19, 2016      0  
23474  January 19, 2016      0  
23475  January 18, 2016      0  
23476  January 16, 2016      0  
23477  January 16, 2016      0  
23478  January 15, 2016      0  
23479  January 14, 2016      0  
23480  January 12, 2016      0  
21407  August 22, 2017       1  
21408  August 22, 2017       1  
21409  August 22, 2017       1  
21410  August 22, 2017       1  
21411  August 21, 2017       1  
21412  August 22, 2017       1  
21413  August 22, 2017       1  
21414  August 22, 2017       1  
21415  August 22, 2017       1  
21416  August 22, 2017       1

In [12]:
#load the manual dataset into a csvfile
df_manual_testing.to_csv(r"C:\Users\user\Desktop\PYTHON\COMPLETED\fake news classification\manual_testing.csv", encoding="utf_8")

In [13]:
#Now merge df_fake and df_real datasets
df_merge = pd.concat([df_fake, df_real])
df_merge.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0

In [14]:
#we only require the text and class columns to predict the news as real or fake
#Hence drop the remaining clomuns
df= df_merge.drop(["title", "subject", "date"], axis=1)
df

text  class
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
21402  ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...      1
21403  WASHINGTON (Reuters) - The United States sugge...      1
21404  WASHINGTON (Reuters) - The United States has d...      1
21405  ISLAMABAD (Reuters) - Outlining a new strategy...      1
21406  GENEVA (Reuters) - North Korea and the United ...      1

[44878 rows x 2 columns]

In [15]:
#Check for null vaalues
df.isnull().sum()

text     0
class    0
dtype: int64

In [16]:
# shuffle the DataFrame rows and reset the index
df = df.sample(frac=1).reset_index()
df.head()

index                                               text  class
0   4138  As Donald Trump and his supporters continue to...      0
1   2273  CHICAGO (Reuters) - Chicago on Monday sued to ...      1
2  22198  21st Century Wire says Is this the biggest new...      0
3  20624  Tell that to the 87 year old woman who was rap...      0
4   4774  WASHINGTON (Reuters) - The head of the U.S. Ho...      1

In [17]:
df.columns

Index(['index', 'text', 'class'], dtype='object')

In [18]:
df.drop("index", axis=1, inplace= True)

In [19]:
df.head()

text  class
0  As Donald Trump and his supporters continue to...      0
1  CHICAGO (Reuters) - Chicago on Monday sued to ...      1
2  21st Century Wire says Is this the biggest new...      0
3  Tell that to the 87 year old woman who was rap...      0
4  WASHINGTON (Reuters) - The head of the U.S. Ho...      1

In [20]:
df.columns

Index(['text', 'class'], dtype='object')

In [21]:
#create a function to convert the text into a lowercase n remove all the extra characters, punctuations, url,etc
import re
import string
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text) 
    return text   

In [22]:
#Apply the above function to the text column
df["text"] = df["text"].apply(wordopt)
df["text"]

0        as donald trump and his supporters continue to...
1        chicago  reuters    chicago on monday sued to ...
2         century wire says is this the biggest new nug...
3        tell that to the  year old woman who was raped...
4        washington  reuters    the head of the u s  ho...
                               ...                        
44873    seoul  reuters    north korea s goal is reachi...
44874    washington  reuters    u s  president elect do...
44875    cairo  reuters    the egyptian military said o...
44876    berlin  reuters    german chancellor angela me...
44877    bad news for donald trump  despite his objecti...
Name: text, Length: 44878, dtype: object

In [23]:
# Define the independent and Dependent variable 
X = df["text"]  #Independent
y = df["class"] #Dependent

In [24]:
#Split the data into training and testing datsets with testdata of 25%
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(33658,)
(11220,)
(33658,)
(11220,)


In [26]:
#convert the text to vectors
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization = TfidfVectorizer()
xv_train =vectorization.fit_transform(X_train)
xv_test = vectorization.transform(X_test)

In [27]:
print(xv_train.shape)
print(xv_test.shape)

(33658, 95173)
(11220, 95173)


#### 1. Logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [29]:
pred_LR = LR.predict(xv_test)
pred_LR

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [30]:
#testing score
LR.score(xv_test, y_test)

0.9890374331550802

In [31]:
confusion_matrix(y_test, pred_LR)

array([[5785,   67],
       [  56, 5312]], dtype=int64)

In [32]:
print(classification_report(y_test, pred_LR))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5852
           1       0.99      0.99      0.99      5368

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220



#### 2. Decision Tree Classification

In [33]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [34]:
pred_DT = DT.predict(xv_test)
pred_DT

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [35]:
DT.score(xv_test, y_test)

0.9963458110516934

In [36]:
confusion_matrix(y_test, pred_DT)

array([[5833,   19],
       [  22, 5346]], dtype=int64)

In [37]:
print(classification_report(y_test, pred_DT))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5852
           1       1.00      1.00      1.00      5368

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220



#### 3. Gradient Boosting Classifier

In [38]:
from sklearn.ensemble import GradientBoostingClassifier

In [39]:
GB = GradientBoostingClassifier()
GB.fit(xv_train, y_train)

GradientBoostingClassifier()

In [40]:
pred_GB = GB.predict(xv_test)
pred_GB

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [41]:
GB.score(xv_test, y_test)

0.9947415329768271

In [42]:
confusion_matrix(y_test, pred_GB)

array([[5803,   49],
       [  10, 5358]], dtype=int64)

In [43]:
print(classification_report(y_test, pred_GB))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      5852
           1       0.99      1.00      0.99      5368

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220



#### 4. Random Forest Classifier

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
RF = RandomForestClassifier()
RF.fit(xv_train, y_train)

RandomForestClassifier()

In [46]:
pred_RF = RF.predict(xv_test)

In [47]:
RF.score(xv_test, y_test)

0.9907308377896613

In [48]:
confusion_matrix(y_test, pred_RF)

array([[5813,   39],
       [  65, 5303]], dtype=int64)

In [49]:
print(classification_report(y_test, pred_RF))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5852
           1       0.99      0.99      0.99      5368

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220



# Model Testing Using Manual Entry

### News

In [50]:
def results(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Real News"
            

def manual_test(news):
    test_news = {"text" : [news]} #create a news dictionary 
    df1 = pd.DataFrame(test_news)   #load dictionary into a dataframe for testing
            # aplly the wordopt function df["text"] to convert the text into a lowercase 
            #n remove all the extra characters, punctuations, url,etc

    df1["text"] = df1["text"].apply(wordopt)
    X1 = df1["text"]  #create a variable for input text news 
    XV1 = vectorization.transform(X1) #transform the news text variable into a vector
    # find the predictive variable of all the above four test
    pred_LR1 = LR.predict(XV1)
    pred_DT1 = DT.predict(XV1)
    pred_GB1 = GB.predict(XV1)
    pred_RF1 = RF.predict(XV1)

    #put these prediction variables in the results function 

    return("1)LR Prediction: {}  2)DT Prediction: {}  3)GB Prediction: {} 4)RF Prediction: {}" .format(results(pred_LR1[0]),
                   results(pred_DT1[0]),
                   results(pred_GB1[0]),
                   results(pred_RF1[0]))
           )


In [51]:
news = str(input())
manual_test(news)

Social networks are fertile ground for spreading lies that are knowingly presented as legitimate information. Exposing them is often simple. Critical thinking, civic-mindedness, and media education can often suffice to foil misinformers’ strategies.  However, doctored videos, called deep fakes, are in certain cases more and more difficult to identify as such. These composite videos create an illusion of authentic filming. They are created thanks to an image synthesis technique coming from artificial intelligence, which makes it possible to convincingly change someone’s face for example.  Yet, videos viewed by a large number of people can cause social tension, influence voters’ decisions, or still damage businesses’ or people’s reputation.  The arms race The ensuing “technological arms race” opposes two “sides” that are entwined, like the two networks of a GAN (Generative Adversarial Network), the technology that is often at the origin of deep fakes but that also enables uncovering of f

'1)LR Prediction: Fake News  2)DT Prediction: Fake News  3)GB Prediction: Fake News 4)RF Prediction: Fake News'